services:
  - type: web
    name: mon-app-epargne
    env: python
    buildCommand: poetry install --no-dev
    startCommand: poetry run gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4