services:
  - type: web
    name: mon-app-epargne
    env: python
    buildCommand: poetry install --no-dev --no-interaction
    startCommand: poetry run gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: POETRY_VERSION
        value: 2.1.3